from openaiTest import *
import re
import random
import io
from PIL import Image
from flask import Flask, render_template, request, send_file, session

query1 = """
Please generate 20 news genre/type/feature/trait eg. sports, politics, entertainment,
investigation, opinion etc. and put them in brackets like <sports>, <politics>, ...
"""
query2 = """
Be creative and goofy and crazy and out of the box. Think of something that has never
been thought of before.
"""
query3 = """
Generate a news headline based on the following user search request and news genres, and
put the headline in brackets like <headline>.
"""
query4 = """
Generate a news article based on the following headline and news genres.
"""
query5 = """
You are receiving a portion of a news article. Please write a concise text prompt for a news image
inserted in the article after this portion, your response should be less than 20 words.
"""



# Write a function that takes a string and returns a list of new genres by identifying <> tags
def get_genres(str):
    return re.findall(r'<(.*?)>', str)

# Write a function that returns genres generated by the AI
def get_ai_genres(query1, query2):
    return get_genres(ask_question(query1+query2))

# Write a function that returns a list of news genres both relevant and creative
def get_meta_genres(user_search):
    user_search = "Based on the user search history: " + user_search
    return list(set(get_ai_genres(query1, user_search) + get_ai_genres(query1, query2)))
    
# write a function to randomly select 5 genres from the list of genres
def get_random_genres(genres):
    return random.sample(genres, 5)

# write a function that returns a headline based on the user search and the genres
def get_headline(user_search, genres):
    user_search = "User search request: " + user_search
    genres = "News genres: " + ', '.join(genres)
    str = ask_question(query3 + user_search + genres)
    return re.findall(r'<(.*?)>', str)[0]

# write a function that generate a list of tuples of (headline, genres) based on the user search
def get_headlines(user_search, n):
    genres_broad = get_meta_genres(user_search)
    genres_lst = []
    tuples = []
    for i in range(n):
        genres_lst.append(get_random_genres(genres_broad))
    for genres in genres_lst:
        tuples.append((get_headline(user_search, genres), genres))
    return tuples

# Write a function that based on a headline and genres, generates a news article
def get_article(headline, genres):
    headline = "Headline: " + headline
    genres = "Genres: " + ', '.join(genres)
    return ask_question(query4 + headline + genres)

# Write a function that given a string article, returns a list of sentences divided by newline
def get_sentences(article):
    return article.split('\n')

# Write a function that splits a string article into n portions
def split_article(article, n):
    res = []
    sentences = get_sentences(article)
    length = len(sentences)
    portion_length = length//n
    portions = [sentences[i:i+portion_length] for i in range(0, length, portion_length)]
    for portion in portions:
        portion = '\n'.join(portion)
        res.append(portion)
    return res

# Write a function that given an article portion, returns a text prompt for news image
def get_image_prompt(portion):
    portion = "Article portion: " + portion
    result = ask_question(query5 + portion)
    return result

# Write a function that given a text prompt, returns an image in URL format
def get_image(prompt):
    res = request_image(prompt)
    assert(isinstance(res, str))
    return str(res)


"""
userInput = input("Enter a search query to this database: ")
testHeadlines = get_headlines(userInput, 5)
print(testHeadlines)
userInput = input("Enter the number of the headline you want to read: ")
testArticle = get_article(testHeadlines[int(userInput)-1][0], testHeadlines[int(userInput)-1][1])


testPortions = split_article(testArticle, 3)
testPrompts = [get_image_prompt(portion) for portion in testPortions]
testImages = [get_image(prompt) for prompt in testPrompts]
testNewsFormat = list(zip(testPortions,testImages, testPrompts))

print(testNewsFormat)

"""